version: '3'
services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:     
      - .:/go/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
   
volumes:
  app: 
